apiVersion: v1
kind: Service 
metadata: 
  labels:
    app: nginx-multitool
  name: nginx-multitool
  namespace: test 
spec:  
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 80
    name: http-port
  - port: 9002
    protocol: TCP
    targetPort: 8080
    name: http-multitool 
  selector:
    app: nginx-multitool 
  type: ClusterIP