apiVersion: v1
kind: Service
metadata:
  name: netoloy
  labels:
    app: netoloy
spec:
  ports:
  - nodePort: 30003
    port: 80
    protocol: TCP
    targetPort: 80
    name: nginx
  - nodePort: 30001
    port: 1180
    protocol: TCP
    targetPort: 1180
    name: multitool-http
  - nodePort: 30002
    port: 11443
    protocol: TCP
    targetPort: 11443
    name: multitool-https
  selector:
    app: netology
  type: NodePort
