apiVersion: apps/v1
kind: Deployment
metadata: 
  generation: 1
  labels:
    app: nginx
  name: nginx
  namespace: test 
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      initContainers:
      - image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', "until nslookup nginxservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for nginxservice; sleep 2; done"]
        name: nginx-service 
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      