apiVersion: v1
kind: Pod
metadata:
  name: static-web
spec:
  initContainers:
    - name: init
      image: alpine
      command: ['sh', '-c', 'sleep 10 && echo "running"']
  containers:
    - name: app
      image: alpine
      command: ['sh', '-c', 'echo "app is running" && sleep infinity']

